<?php

/**
 * @file
 * DropShark module code.
 */

define('DROPSHARK_HOST_DEFAULT', 'http://data.dropshark.io');
define('DROPSHARK_QUEUE_DEFAULT', 'DropSharkDbQueue');
define('DROPSHARK_QUEUE_LOCK_MAX_DEFAULT', 300);
define('DROPSHARK_QUEUE_MAX_PROCESS_DEFAULT', 100);
define('DROPSHARK_REQUEST_DEFAULT', 'DropSharkRequestDefault');

/**
 * Implements hook_menu().
 */
function dropshark_menu() {
  $items['admin/config/services/dropshark'] = array(
    'type' => MENU_NORMAL_ITEM,
    'title' => 'DropShark',
    'description' => 'Configure your site to utilize the DropShark monitoring, trending, and alerts service.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dropshark_admin_config'),
    'access arguments' => array('administer site configuration'),
    'file' => 'dropshark.admin.inc',
  );

  return $items;
}

/**
 * Gets the configured DropShark queue processing class.
 *
 * @return DropSharkQueue
 *   The queue processor configured for use.
 */
function dropshark_get_queue() {
  $queue = &drupal_static(__FUNCTION__);

  if (!$queue) {
    $request_class = variable_get('dropshark_request_class', DROPSHARK_REQUEST_DEFAULT);
    $class = variable_get('dropshark_queue_class', DROPSHARK_QUEUE_DEFAULT);
    $request = new $request_class();
    $queue = new $class($request);
  }

  return $queue;
}

/**
 * Set data to be added to the queue
 *
 * Data is held in a static queue and added to the processing queue at the end
 * of the page request.
 *
 * @param array $data
 *   Data to add to the static queue.
 * @param bool $reset
 *   Reset the static queue.
 *
 * @return array
 *   The queued data.
 */
function dropshark_queue_data($data = NULL, $reset = FALSE) {
  static $queue = array();
  static $registered = FALSE;

  if (!$registered) {
    drupal_register_shutdown_function('dropshark_queue_request_data');
    $registered = TRUE;
  }

  if ($reset) {
    $queue = array();
  }

  if ($data !== NULL) {
    $queue[] = $data;
  }

  return $queue;
}

/**
 * Save data from static request queue into persistent a queue.
 */
function dropshark_queue_request_data() {
  // TODO: investigate adding multiple queued data items in a single call.
  $queue = dropshark_get_queue();
  foreach (dropshark_queue_data() as $data) {
    $queue->add($data);
  }
  dropshark_queue_data(NULL, TRUE);
}

/**
 * Process items in the DropShark queue.
 */
function dropshark_queue_process() {
  $queue = dropshark_get_queue();
  $queue->process();
}

/**
 * Get available collectors.
 */
function dropshark_get_collectors($reset = FALSE) {
  $collectors = drupal_static(__FUNCTION__);

  if ($reset || ($collectors === NULL)) {
    if ((!$reset) && $cache = cache_get('dropshark_collector_info')) {
      $collectors = $cache->data;
    } else {
      $hook = 'dropshark_collector_info';
      $collectors = array();
      foreach (module_implements($hook) as $module) {
        module_load_include('inc', $module, $module . '.dropshark');
        $collectors = array_merge($collectors, module_invoke($module, $hook));
      }
      drupal_alter($hook, $collectors);
      cache_set('dropshark_collector_info', $collectors);
    }
  }

  return $collectors;
}

/**
 * Instantiate a collector.
 */
function dropshark_get_collector($collector_id) {
  $collectors = dropshark_get_collectors();

  if (!empty($collectors[$collector_id]['class'])) {
    $class = $collectors[$collector_id]['class'];
    return new $class($collectors[$collector_id]);
  }
}

/**
 * Implements hook_dropshark_collector_info().
 */
function dropshark_dropshark_collector_info() {
  $collectors['disk'] = array(
    'class' => 'DropSharkDiskCollector',
    'groups' => array('system'),
  );

  $collectors['drupal_status'] = array(
    'class' => 'DropSharkDrupalStatusCollector',
    'groups' => array('drupal'),
  );

  $collectors['memory'] = array(
    'class' => 'DropSharkMemoryCollector',
    'groups' => array('system'),
  );

  $collectors['opcache'] = array(
    'class' => 'DropSharkPhpOpcacheCollector',
    'groups' => array('system'),
  );

  $collectors['swap'] = array(
    'class' => 'DropSharkSwapCollector',
    'groups' => array('system'),
  );

  return $collectors;
}
