<?php

/**
 * @file
 * DropShark module code.
 */

define('DROPSHARK_HOST_DEFAULT', 'https://data.dropshark.io');
define('DROPSHARK_QUEUE_DEFAULT', 'DropSharkDbQueue');
define('DROPSHARK_QUEUE_LOCK_MAX_DEFAULT', 300);
define('DROPSHARK_QUEUE_MAX_PROCESS_DEFAULT', 100);
define('DROPSHARK_REQUEST_DEFAULT', 'DropSharkRequest');
define('DROPSHARK_LINFO_AUTOLOADER', 'libraries/linfo/standalone_autoload.php');

/**
 * Registers dropshark_finalize_request() as a shutdown function.
 */
function dropshark_set_shutdown_function() {
  static $registered = FALSE;

  if (!$registered) {
    drupal_register_shutdown_function('dropshark_finalize_request');
    $registered = TRUE;
  }
}

/**
 * Finish processing on the end of the page request.
 *
 * Runs collectors which have been deferred until the end of the request, then
 * saves data from static request queue into persistent a queue.
 */
function dropshark_finalize_request() {
  /** @var \Drupal\dropshark\Queue\QueueInterface $queue */
  $queue = Drupal::service('dropshark.queue');

  // Perform deferred processing.
  $queue->processDeferred();

  // Transmit if immediate transmit is indicated.
  if ($queue->needsImmediateTransmit()) {
    $queue->transmit();
  }

  // Persistently store remaining items.
  $queue->persist();
}

/**
 * Instantiate the Linfo library.
 *
 * @return \Linfo\Linfo|false
 *   The Linfo library, or FALSE if not present.
 */
function dropshark_get_linfo() {
  // @TODO: refactor/eliminate?
  $linfo = &drupal_static(__FUNCTION__, NULL);

  if ($linfo === NULL) {
    // @todo: dynamic settings handling.
    $settings['show']['mounts_options'] = FALSE;

    // If not available via Composer, attempt to use the built-in autoloader.
    if (!class_exists('\Linfo\Linfo')) {
      $file = DROPSHARK_LINFO_AUTOLOADER;
      if (file_exists(DROPSHARK_LINFO_AUTOLOADER)) {
        include $file;
      }
    }

    // If it's still not there, then we can't do anything.
    if (!class_exists('\Linfo\Linfo')) {
      return $linfo = FALSE;
    }

    $linfo = new \Linfo\Linfo($settings);
  }

  return $linfo;
}

/**
 * Implements hook_cron().
 */
function dropshark_cron() {
  // Get the plugin manager, invoke collection w/immediate transmit.
}
