dropshark.settings:
  type: config_object
  label: 'Dropshark settings'
  mapping:
    host:
      type: string
      label: 'DropShark backend host'
    cron:
      type: boolean
      label: 'Recursion limit for actions'
    queue:
      type: mapping
      label: 'Queue configuration'
      mapping:
        lock_max:
          type: integer
          label: 'Maximum lock duration'
        max_process:
          type: integer
          label: 'Maximum number of items to process in a single run'
    linfo_path:
      type: string
      label: 'Location of the Linfo autoloader file'
